document.addEventListener('DOMContentLoaded', () => {
    const btn = document.getElementById('generateBtn');
    const outputArea = document.getElementById('outputArea');
    const textarea = document.getElementById('makefileOutput');
    const copyBtn = document.getElementById('copyBtn');
    const radioC = document.getElementById('langC');
    const radioCpp = document.getElementById('langCpp');

    btn.addEventListener('click', generateMakefile);

    copyBtn.addEventListener('click', () => {
        textarea.select();
        document.execCommand('copy');
        copyBtn.textContent = "Copied!";
        setTimeout(() => copyBtn.textContent = "Copy", 2000);
    });

    function generateMakefile() {
        // 1. Config
        const isCpp = radioCpp.checked;
        const cc = isCpp ? "CXX" : "CC";
        const compiler = isCpp ? "g++" : "gcc";
        const ext = isCpp ? ".cpp" : ".c";
        const std = isCpp ? "-std=c++20" : "-std=c99";
        
        // 2. Variables
        const binName = sanitize(document.getElementById('binName').value) || "httpd";
        let srcDir = sanitizePath(document.getElementById('srcDir').value) || "src";
        if (srcDir.endsWith('/')) srcDir = srcDir.slice(0, -1);

        const isRecursive = document.getElementById('featRecursive').checked;
        const usePython = document.getElementById('featPython').checked;
        const useCoverage = document.getElementById('featCoverage').checked; // Checkbox Coverage
        const usePthread = document.getElementById('flagPthread').checked;

        // 3. Flags
        let flags = `${std} -Werror -Wall -Wextra -Wvla -pedantic`;
        let ldflags = "";
        if (usePthread) ldflags += "-pthread";

        // 4. Source Discovery
        let srcsDef;
        if (isRecursive) {
            srcsDef = `SRCS := $(shell find ${srcDir} -name '*${ext}')`;
        } else {
            srcsDef = `SRCS = $(wildcard ${srcDir}/*${ext})`;
        }

        // 5. Template Base
        let makefile = `# Advanced Makefile generated by System Tools | @Buzzcut
${cc} = ${compiler}
TARGET = ${binName}
CFLAGS = ${flags}
CPPFLAGS = -I${srcDir}/
LDFLAGS = ${ldflags}

# Source Discovery
${srcsDef}
OBJS = $(SRCS:${ext}=.o)

all: $(TARGET)

$(TARGET): $(OBJS)
\t$(${cc}) $(OBJS) -o $(TARGET) $(LDFLAGS)

# Compilation Rule
%${ext.replace('.','')}.o: %${ext}
\t$(${cc}) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

# Debug Build
debug: LDFLAGS += -fsanitize=address
debug: CFLAGS += -g -fsanitize=address
debug: clean $(TARGET)

`;
        if (usePython) {
            makefile += `# Python Testing Environment
TEST_ENV = test_env
REQ_FILE = tests/requirements.txt
PYTEST_DIR = tests/py_tests

check: debug
\t@ echo "Running Python Tests..."
\t@ python3 -m venv $(TEST_ENV)
\t@ $(TEST_ENV)/bin/pip install -r $(REQ_FILE)
\t@ $(TEST_ENV)/bin/pytest -c $(PYTEST_DIR)/pytest.ini $(PYTEST_DIR)/
\t@ rm -rf $(TEST_ENV)

valgrind: clean $(TARGET)
\t@ echo "Running Valgrind + Pytest..."
\t@ python3 -m venv $(TEST_ENV)
\t@ $(TEST_ENV)/bin/pip install -r $(REQ_FILE)
\t@ USE_VALGRIND=1 $(TEST_ENV)/bin/pytest -c $(PYTEST_DIR)/pytest.ini $(PYTEST_DIR)/
\t@ rm -rf $(TEST_ENV)
`;
        } else {
            makefile += `check: debug
\t@echo "Running basic tests..."
\t./tests/test_all.sh
`;
        }
        if (useCoverage) {
            makefile += `
# Code Coverage
coverage: CFLAGS += --coverage -fPIC
coverage: LDFLAGS += --coverage
coverage: LDLIBS += -lgcov
coverage: clean all
\tmake check
\tmkdir -p coverage
\tlcov --capture --directory ${srcDir} --output-file coverage.info
\tgenhtml coverage.info --output-directory coverage
\t@echo "Coverage report generated in coverage/index.html"
\tfirefox coverage/index.html &
`;
        }
        makefile += `
clean:
\trm -f $(OBJS) $(TARGET)
\trm -rf $(TEST_ENV) __pycache__ .pytest_cache
\trm -rf coverage coverage.info
\tfind . -name "*.gcda" -delete
\tfind . -name "*.gcno" -delete

.PHONY: all clean check debug valgrind coverage
`;

        textarea.value = makefile;
        outputArea.style.display = 'block';
        outputArea.scrollIntoView({ behavior: 'smooth' });
    }

    function sanitize(str) { return str.replace(/[^a-zA-Z0-9_\-\.]/g, ''); }
    function sanitizePath(str) { return str.replace(/[^a-zA-Z0-9_\-\.\/]/g, ''); }
});
