document.addEventListener('DOMContentLoaded', () => {
    const btn = document.getElementById('genBtn');
    const output = document.getElementById('output');
    const copyBtn = document.getElementById('copyBtn');
    const options = document.querySelectorAll('.cat-option');

    // UI Toggle
    options.forEach(opt => {
        opt.addEventListener('click', () => {
            options.forEach(o => o.classList.remove('active'));
            opt.classList.add('active');
        });
    });

    btn.addEventListener('click', generateScript);

    copyBtn.addEventListener('click', () => {
        output.select();
        document.execCommand('copy');
        copyBtn.textContent = "Copied!";
        setTimeout(() => copyBtn.textContent = "Copy", 1000);
    });

    // --- RANDOMIZER ENGINE (Anti-Cheat) ---
    
    function rndVar() {
        const prefixes = ["VAR", "TEST", "DATA", "MY_VAL", "RES", "TMP", "IDX", "PTR", "BUF"];
        const suffix = Math.random().toString(36).substring(2, 6).toUpperCase();
        return `${prefixes[Math.floor(Math.random() * prefixes.length)]}_${suffix}`;
    }

    function rndFile() {
        const names = ["dump", "log", "out", "trace", "res", "buffer", "stream"];
        const ext = ["txt", "log", "dat", "tmp"];
        return `${names[Math.floor(Math.random() * names.length)]}_${Math.floor(Math.random() * 1000)}.${ext[Math.floor(Math.random() * ext.length)]}`;
    }

    function rndStr() {
        const words = ["42sh", "shell", "test", "epita", "unix", "posix", "kernel", "stack", "heap", "crash", "segfault", "void"];
        return words[Math.floor(Math.random() * words.length)] + "_" + Math.floor(Math.random() * 100);
    }

    function rndInt(min, max) {
        return Math.floor(Math.random() * (max - min + 1)) + min;
    }

    // --- GENERATEUR ---

    function generateScript() {
        const category = document.querySelector('input[name="category"]:checked').value;
        const lineCountInput = document.getElementById('lineCount');
        const lineCount = lineCountInput ? parseInt(lineCountInput.value) : 10;

        const timestamp = new Date().toISOString();
        const seed = Math.random().toString(36).substring(7);
        
        let content = `#!/bin/sh
# 42sh Functional Test - Category: ${category.toUpperCase()}
# Generated by System Tools (Polymorphic Engine) by @Buzzcut
# Seed: ${seed} | Date: ${timestamp}

`;

        for (let i = 0; i < lineCount; i++) {
            content += `\n# --- Test Case ${i + 1} ---\n`;
            
            switch(category) {
                case 'flow': content += getFlowTests(); break;
                case 'redir': content += getRedirTests(); break;
                case 'builtins': content += getBuiltinTests(); break;
                case 'expansion': content += getExpansionTests(); break;
                case 'torture': content += getTortureTests(); break;
            }
            content += "\n";
        }

        output.value = content;
    }

    // --- TEMPLATES DYNAMIQUES (Raw Logic) ---

    function getFlowTests() {
        const v1 = rndVar();
        const v2 = rndVar();
        const valA = rndStr();
        const valB = rndStr();
        const loopMax = rndInt(2, 5);

        const type = rndInt(1, 3);

        if (type === 1) {
            return `echo "Testing Loop ${rndInt(1,999)}"
for i in $(seq 1 ${rndInt(2,4)}); do
    echo "Outer $i"
    if [ "$i" = "2" ]; then
        echo "Conditional Break"
        break
    fi
done`;
        } else if (type === 2) {
            return `${v1}="${valA}"
case "$${v1}" in
    ${valB}) echo "Fail case" ;;
    ${valA}) echo "Match OK: ${valA}" ;;
    *)       echo "Default" ;;
esac`;
        } else {
            return `${v2}=0
until [ "$${v2}" -ge ${loopMax} ]; do
    echo "Counter: $${v2}"
    ${v2}=$(( $${v2} + 1 ))
done`;
        }
    }

    function getRedirTests() {
        const f1 = rndFile();
        const f2 = rndFile();
        const msg = rndStr();
        const type = rndInt(1, 4);

        if (type === 1) {
            return `echo "${msg}" > ${f1}
cat < ${f1}
rm -f ${f1}`;
        } else if (type === 2) {
            return `ls /file_not_found_${rndInt(1000,9000)} 2>&1 | grep "No such file" && echo "Stderr Redirect OK"`;
        } else if (type === 3) {
            return `echo "Start Log" > ${f2}
echo "Append Log" >> ${f2}
cat ${f2}
rm -f ${f2}`;
        } else {
            return `echo "${rndStr()}" | tr 'a-z' 'A-Z' > ${f1}
cat ${f1}
rm -f ${f1}`;
        }
    }

    function getBuiltinTests() {
        const dir = "dir_" + rndInt(100, 999);
        const vEnv = rndVar();
        const valEnv = rndStr();
        const type = rndInt(1, 3);

        if (type === 1) {
            return `mkdir -p ${dir}
cd ${dir}
echo "PWD Check: $PWD"
cd ..
rm -rf ${dir}`;
        } else if (type === 2) {
            return `export ${vEnv}="${valEnv}"
sh -c 'echo "Child: $${vEnv}"'
unset ${vEnv}`;
        } else {
            return `( exit ${rndInt(1, 127)} )
echo "Exit status: $?"`;
        }
    }

    function getExpansionTests() {
        const v1 = rndVar();
        const val = "Val_" + rndInt(1000, 9999);
        const type = rndInt(1, 3);

        if (type === 1) {
            return `echo "Subshell: $(echo start $(echo inner_${rndInt(1,9)}) end)"`;
        } else if (type === 2) {
            return `${v1}="${val}"
echo "Var: \${${v1}}_Suffix"`;
        } else {
            return `echo "Quote Mix: 'Single' \\"Double\\" ${rndStr()}"`;
        }
    }

    function getTortureTests() {
        const type = rndInt(1, 3);
        
        if (type === 1) {
            return `# Subshell Logic Bomb
(
    exit 5
)
[ "$?" -eq 5 ] && echo "Deep exit captured"`;
        } else if (type === 2) {
            return `true && echo "${rndStr()}" || echo "Fail" && false || echo "Recovery_OK"`;
        } else {
            return `false | true
echo "Pipe status: $?"`;
        }
    }
});
