document.addEventListener('DOMContentLoaded', () => {
    const inputTree = document.getElementById('inputTree');
    const output = document.getElementById('output');
    const convertBtn = document.getElementById('convertBtn');
    const copyBtn = document.getElementById('copyBtn');

    convertBtn.addEventListener('click', parseTree);
    copyBtn.addEventListener('click', copyCommands);

    function parseTree() {
        const rawText = inputTree.value;
        if (!rawText.trim()) {
            output.value = "# Please paste a file tree structure on the left.";
            return;
        }

        const lines = rawText.split('\n');
        let commands = ["#!/bin/sh", "# Generated by Project Tree Builder", ""];
        
        
        let pathStack = []; 
        let lastDepth = -1;

        lines.forEach((line, index) => {
            
            let cleanLine = line.replace(/\(to submit\)/gi, "")
                                .replace(/\(optional\)/gi, "")
                                .replace(/\s*#.*$/, ""); 

            
            if (!cleanLine.trim()) return;

            
            const depthInfo = getDepthAndName(cleanLine);
            let name = depthInfo.name;
            let depth = depthInfo.depth;

            
            if (name === "." || name === "./") return;

            
            
            if (depth <= lastDepth) {
                
                
                pathStack = pathStack.slice(0, depth);
            }

            
            
            let isFolder = name.endsWith("/") || !name.includes("."); 
            
            
            if (["Makefile", "configure", ".gitignore", "README", "LICENSE", "AUTHORS"].includes(name)) {
                isFolder = false;
            }
            
            
            if (name.endsWith("/")) name = name.slice(0, -1);

            
            if (name.includes("*") || name.includes("{") || name.includes("?")) {
                
                const tempStack = [...pathStack, name].filter(p => p && p.trim() !== "");
                commands.push(`# [SKIP] Pattern detected: ${tempStack.join('/')}`);
                return; 
            }

            
            
            pathStack[depth] = name;

            
            const relativePath = pathStack.filter(p => p && p.trim() !== "").join('/');

            if (isFolder) {
                commands.push(`mkdir -p "${relativePath}"`);
            } else {
                commands.push(`touch "${relativePath}"`);
            }

            lastDepth = depth;
        });

        commands.push("", "# Done! Don't forget to 'chmod +x' your scripts.");
        output.value = commands.join('\n');
    }

    function getDepthAndName(str) {
        
        
        let treeMatch = str.match(/^[\s│├└─]+/);
        let prefixLen = treeMatch ? treeMatch[0].length : 0;
        
        
        if (!treeMatch) {
            let spaceMatch = str.match(/^\s*/);
            prefixLen = spaceMatch ? spaceMatch[0].length : 0;
        }

        
        
        let depth = Math.floor(prefixLen / 4); 
        
        
        
        if (prefixLen > 0 && prefixLen < 4) depth = 1;

        
        let name = str.replace(/^[\s│├└─]+/, "").trim();

        return { depth, name };
    }

    function copyCommands() {
        output.select();
        document.execCommand('copy');
        const originalText = copyBtn.innerHTML;
        copyBtn.innerHTML = '<i class="fa-solid fa-check"></i> Copied!';
        copyBtn.style.background = "#27ae60";
        setTimeout(() => {
            copyBtn.innerHTML = originalText;
            copyBtn.style.background = "#333";
        }, 2000);
    }
});
