-- =================================================================
-- CONFIGURATION HYPRLAND (LUA) - PERSONNALISÉE POUR KALOU
-- =================================================================

-- Supprime l'avertissement d'autogénération
hl.config({ autogenerated = false })

------------------
---- MONITORS ----
------------------
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

---------------------
---- MY PROGRAMS ----
---------------------
local terminal    = "kitty"
local fileManager = "thunar"
local menu        = "wofi --show drun"

-------------------
---- AUTOSTART ----
-------------------
hl.on("hyprland.start", function () 
    hl.exec_cmd("killall -q waybar; waybar &")
    hl.exec_cmd("killall -q hyprpaper; hyprpaper &")
    
    hl.exec_cmd("hyprctl keyword windowrulev2 'float, class:^(org.gnome.Calendar)$'")
    hl.exec_cmd("hyprctl keyword windowrulev2 'size 900 650, class:^(org.gnome.Calendar)$'")
    hl.exec_cmd("hyprctl keyword windowrulev2 'center, class:^(org.gnome.Calendar)$'")

    hl.exec_cmd("hyprctl keyword layerrule 'blur, logout_dialog'")
    hl.exec_cmd("hyprctl keyword layerrule 'ignorealpha 0.5, logout_dialog'")

    hl.exec_cmd("hyprctl keyword layerrule 'blur, wofi'")

    hl.exec_cmd("hyprctl keyword layerrule 'ignorealpha 0.5, wofi'")
    hl.exec_cmd("hyprctl keyword layerrule 'blur, notifications'")
    hl.exec_cmd("hyprctl keyword layerrule 'ignorealpha 0.2, notifications'")

    -- Audio control
    hl.exec_cmd("hyprctl keyword bindel ', XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+'")
    hl.exec_cmd("hyprctl keyword bindel ', XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'")
    hl.exec_cmd("hyprctl keyword bindel ', XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'")

    -- Brightness control
    hl.exec_cmd("hyprctl keyword bindel ', XF86MonBrightnessUp, exec, brightnessctl set 5%+'")
    hl.exec_cmd("hyprctl keyword bindel ', XF86MonBrightnessDown, exec, brightnessctl set 5%-'")


    hl.exec_cmd("hyprsunset &")

    hl.exec_cmd("~/.config/hypr/scripts/mode-switcher.sh --default detente")

    hl.exec_cmd("rfkill unblock bluetooth")
    hl.exec_cmd("/usr/lib/hyprpolkitagent &")

    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")

end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-----------------------
---- LOOK AND FEEL ----
-----------------------
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 10,
        border_size = 2,
        col = {
            active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

----------------
----  MISC  ----
----------------
hl.config({
    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo   = true,
    },
})

---------------
---- INPUT ----
---------------
hl.config({
    input = {
        kb_layout  = "gb", -- Clavier configuré en GB
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,
        sensitivity  = 0,

        touchpad = {
            natural_scroll = true,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

---------------------
---- KEYBINDINGS ----
---------------------
local mainMod = "SUPER" -- Touche Windows

-- Applications & Système
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exit())
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = 0 }))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("wlogout"))
hl.bind("Print", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/screenshot.sh"))
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("kitty -e btop"))
hl.bind(mainMod .. " + Tab", hl.dsp.exec_cmd("~/.config/hypr/scripts/mode-switcher.sh"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("~/.config/hypr/scripts/quicknote.sh"))


-- Déplacement du focus
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Changement de Workspace (Chiffres 1 à 9 et 0 pour 10) et déplacement de fenêtres
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key,        hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Scroll pour changer de workspace
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Déplacer/Redimensionner avec la souris
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Contrôles Multimédia (Audio & Luminosité)
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),       { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),      { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl set 5%+"),                           { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl set 5%-"),                           { locked = true, repeating = true })
-- Verrouiller l'écran avec Super + L
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))
--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------
hl.window_rule({
    name  = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },
    no_focus = true,
})

