
background {
    monitor =
    path = $HOME/Images/bg.png
    blur_passes = 0
    contrast = 1.0
    brightness = 1.0
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    fade_on_empty = false
    placeholder_text = <i>Mot de passe...</i>
}

auth {
    fingerprint {
        enabled = true
        ready_message = (Scan fingerprint to unlock)
        present_message = Scanning fingerprint
    }
}
